name: sjautobidder
channels:
  - conda-forge
  - defaults
dependencies:
  - conda
  - python=3.8.10
  - pvlib-python
  - pytest
  - prospector
  - flask=2.2.5
  - pip
  - pymongo[srv]
  - dnspython
  - scikit-learn=1.2.2
  - pandas=1.5.3
  - pip:
    - pytest-coverage
    - build
    - black
    - gunicorn
    - flask-cors
